/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import OutrasClasses.Produto;
import OutrasClasses.ProdutoDao;
import OutrasClasses.ProdutoServicos;
import OutrasClasses.Usuario;
import OutrasClasses.UsuarioDao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dyonathan
 */
public class Tela_Estoque extends javax.swing.JFrame {

    ProdutoServicos serviceProduct = new ProdutoServicos(new ProdutoDao());
    public Usuario usuario;

    public Tela_Estoque(Usuario user) {
        initComponents();
        Preencher();
        usuario = user;
    }

    public Tela_Estoque() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_filtrar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_estoque = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_editar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cbb_opcao = new javax.swing.JComboBox<>();
        txt_numero = new javax.swing.JTextField();
        btn_salvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_novoproduto = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        lbl_erro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_filtrar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_filtrar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_filtrarCaretUpdate(evt);
            }
        });

        tbl_estoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Preço", "Quantidade", "Validade"
            }
        ));
        jScrollPane1.setViewportView(tbl_estoque);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Estoque");

        btn_editar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbb_opcao.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        cbb_opcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adicionar", "Subtrair" }));
        jPanel2.add(cbb_opcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 153, -1));

        txt_numero.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_numero.setText("0");
        txt_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numeroActionPerformed(evt);
            }
        });
        jPanel2.add(txt_numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 55, 37));

        btn_salvar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Controle Pratico");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        btn_novoproduto.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_novoproduto.setText("Novo Produto");
        btn_novoproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoprodutoActionPerformed(evt);
            }
        });

        btn_voltar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        btn_excluir.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        lbl_erro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_erro.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(345, 345, 345))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(txt_filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(btn_novoproduto)
                                                .addGap(18, 18, 18)
                                                .addComponent(btn_editar))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(btn_excluir)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btn_voltar))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(lbl_erro, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(txt_filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_novoproduto)
                            .addComponent(btn_editar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_voltar)
                            .addComponent(btn_excluir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_erro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 580));

        setSize(new java.awt.Dimension(816, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numeroActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        Tela_Inicial T_I = new Tela_Inicial(usuario);
        T_I.setVisible(true);

        dispose();
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        Editar();
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_novoprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoprodutoActionPerformed
        Tela_Adicionar_Produto T_A_P = new Tela_Adicionar_Produto(usuario);
        T_A_P.setVisible(true);

        dispose();
    }//GEN-LAST:event_btn_novoprodutoActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        Excluir();
        Preencher();
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void txt_filtrarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_filtrarCaretUpdate
        Preencher();
    }//GEN-LAST:event_txt_filtrarCaretUpdate

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        ControlePratico();
        Preencher();
    }//GEN-LAST:event_btn_salvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Estoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_novoproduto;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JComboBox<String> cbb_opcao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_erro;
    private javax.swing.JTable tbl_estoque;
    private javax.swing.JTextField txt_filtrar;
    private javax.swing.JTextField txt_numero;
    // End of variables declaration//GEN-END:variables
public void Preencher() {
        List<Produto> listaP = serviceProduct.getProdutosNome(txt_filtrar.getText());
        String[] config = {"Id", "Nome", "Preço", "Validade", "Quantidade"};
        DefaultTableModel Modelo = new DefaultTableModel(config, 0);

        for (int i = 0; listaP.size() > i; i++) {
            Produto product = listaP.get(i);
            String[] linha = {
                Integer.toString(product.getId()),
                product.getNome(),
                Double.toString(product.getPreco()),
                product.getValidade(),
                Integer.toString(product.getQuantidade())
            };
            Modelo.addRow(linha);
        }
        tbl_estoque.setModel(Modelo);
    }
    public void ControlePratico() {
        if (tbl_estoque.getSelectedRow() != -1) {
            lbl_erro.setText("");
            int idProduto = Integer.parseInt(tbl_estoque.getValueAt(tbl_estoque.getSelectedRow(), 0).toString());
            try {
                int quantidade = Integer.parseInt(txt_numero.getText().toString());

                if (cbb_opcao.getSelectedItem().toString().equals("Subtrair")) {
                    quantidade = quantidade * -1;
                }
                if (!serviceProduct.controlePratico(idProduto, quantidade)) {
                    lbl_erro.setText("Erro ao atualizar valor");
                }
            } catch (Exception ex) {
                lbl_erro.setText("Valor invalido");
            }
        } else {
            lbl_erro.setText("Selecione um produto");
        }
    }
    public void Excluir() {
        if (tbl_estoque.getSelectedRow() != -1) {

            if (serviceProduct.deleteProduto(Integer.parseInt(tbl_estoque.getValueAt(tbl_estoque.getSelectedRow(), 0).toString()))) {
                lbl_erro.setText("");
            } else {
                lbl_erro.setText("Erro ao Deletar Produto");
            }

        } else {
            lbl_erro.setText("Selecione um Produto");
        }

    }

    public void Editar() {

        if (tbl_estoque.getSelectedRow() != -1) {
            lbl_erro.setText("");

            int id = Integer.parseInt(tbl_estoque.getValueAt(tbl_estoque.getSelectedRow(), 0).toString());

            Tela_Editar_Produto T_E_P = new Tela_Editar_Produto(usuario, id);
            T_E_P.setVisible(true);

            dispose();
        } else {
            lbl_erro.setText("Selecione um Produto");
        }
    }

}
